exclude: ".*/(data|docs/experimental)/.*"
repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.7.0
    hooks:
    -   id: pre-commit-update
        args: [--keep, pre-commit-update]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-vcs-permalinks
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
    -   id: detect-private-key

# Mypy disabled - project does not use type annotations
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.18.2
#     hooks:
#     -   id: mypy
#         additional_dependencies:
#         -   fastapi
#         -   uvicorn
#         args: ["--ignore-missing-imports"]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      # Run the linter
    -   id: ruff
        args: [--fix]
      # Run the formatter
    -   id: ruff-format
